<?php
/**
 * Copyright © 2016 by Orderaw.
 * Created by Long Nguyen.
 * User: longnguyen
 * Date: 08/12/2016
 * Time: 10:23
 */

namespace ivoglent\phpriak\tests;


use ivoglent\phpriak\base\RiakSetup;
use ivoglent\phpriak\tests\models\File;
use MongoDB\BSON\Binary;
use yii\BaseYii;

class FileTest extends \PHPUnit_Framework_TestCase{
    public $key;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        RiakSetup::wakeUp()->init([
            [
                'host' => '192.168.1.10',
                'port' => 8098
            ]
        ]);
        $this->key = '';
    }
    public function testAddNewFile(){
        print "\r\n------------------------------------\r\nUploading file : ";
        $file = new File();
        $file->addFile(dirname(__FILE__).'/Basho_Man_Super.png');
        $key = $file->save();
        print "{$key}";
        $this->assertTrue(TRUE);
        return $key;
    }

    /**
     * @depends testAddNewFile
     */
    public function testGetFile($key){
        $data = (new File())->load($key)->getFile();

        print "\r\n------------------------------------\r\nRetreiving file with " . $key ." : " . base64_encode($data) . PHP_EOL;
        return $this->assertNotEmpty($data);
    }



    /**
     * @depends testAddNewFile
     */
    public function testDeleteFile($key) {
        print "\r\n------------------------------------\r\nDeleting file with key {$key} ";
        $data = (new File())->load($key);
        $result = $data->delete();
        $this->assertTrue($result, 'Delete failed');
    }
}