<?php
/**
 * Riak File Model
 * To help store file into riak database
 * Created by Long Nguyen.
 * Contact: ivoglent@gmail.com
 * Project: phpriak
 * Date: 08/12/2016
 * Time: 09:47
 * Version : 1.0.1
 */

namespace ivoglent\phpriak;


use ivoglent\phpriak\base\RiakModel;

abstract class FileModel extends RiakModel
{
    const BUCKET_NAME= 'files';
    /**
     * Get bucket name
     * @return string
     */
    public function getBucketName() {
        // TODO: Implement getBucket() method.
        return self::BUCKET_NAME;
    }

    /**
     * Set bucket name
     * @param string $bucket
     * @return $this
     */
    public function setBucket($bucket) {
        // TODO: Implement setBucket() method.
        $this->bucket = $bucket;
    }
    /**
     * Metadata related to this file
     * contains additional info about this
     * it must be updated when the file changed
     * @var DataModel
     */
    private $dataModel;

    /**
     * Set data model releated to this file
     * @param \ivoglent\phpriak\DataModel $dataModel
     */
    public function setDataModel(DataModel $dataModel){
        $this->dataModel = $dataModel;
    }

    /**
     * Get related data model
     * @return \ivoglent\phpriak\DataModel | null
     */
    public function getDataModel(){
        return $this->dataModel;
    }

    /**
     * Some tasks must be done after file was changed
     * - Update data model
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes) {

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * When this file was deleted
     * we have to delete related data too
     */
    public function afterDelete() {
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
    
    
    public function save($runValidation = TRUE, $attributeNames = NULL) {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
    
}