<?php
/**
 * Riak Base Model
 * Created by Long Nguyen.
 * Contact: ivoglent@gmail.com
 * Project: YiiRiak
 * Date: 08/12/2016
 * Time: 09:47
 * Version : 1.0.1
 */

namespace ivoglent\yiiriak\base;


use Basho\Riak;
use ivoglent\yiiriak\interfaces\RiakModelInterface;
use yii\db\ActiveRecord;

abstract class RiakModel extends ActiveRecord implements RiakModelInterface
{
    protected $bucket;
    private $key = '';
    private $riak;
    public function __construct(array $config = []) {
        parent::__construct($config);
        $this->riak = new Riak([], $config);
    }

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->key)) {
            $response = (new \Basho\Riak\Command\Builder\StoreObject($this->riak))
                ->buildBucket('random_user_keys', $this->getBucket())
                ->buildJsonObject(['user'=>'data'])
                ->build()
                ->execute();
            $this->key = $response->getLocation()->getKey();
        }
    }

    /**
     * save
     * @param bool $runValidation
     * @param null $attributeNames
     * @return bool
     */
    public function save($runValidation = TRUE, $attributeNames = NULL) {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }


    /**
     * delete
     * @return false|int
     * @throws \Exception
     */
    public function delete() {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * update
     * @param bool $runValidation
     * @param null $attributeNames
     * @return false|int
     * @throws \Exception
     */
    public function update($runValidation = TRUE, $attributeNames = NULL) {

    }

    /**
     * insert
     * @param bool $runValidation
     * @param null $attributes
     * @return bool
     * @throws \Exception
     */
    public function insert($runValidation = TRUE, $attributes = NULL) {

    }

    public function getKey(){
        return $this->key;
    }
}