<?php
/**
 * Riak Base Model
 * Created by Long Nguyen.
 * Contact: ivoglent@gmail.com
 * Project: phpriak
 * Date: 08/12/2016
 * Time: 09:47
 * Version : 1.0.1
 */

namespace ivoglent\phpriak\base;


use Basho\Riak;
use ivoglent\phpriak\interfaces\RiakModelInterface;

abstract class RiakModel implements RiakModelInterface
{
    /** @var  Riak\Bucket */
    protected $bucket;
    /** @var  string */
    private $key = '';
    /** @var  Riak $riak */
    private $riak;

    /**
     * @var array
     */
    private $config = [
        'host' => 'localhost',
        'port' => 8098
    ];

    public $dns;

    private $_data = [];


    public function __construct($config = []) {
        if (!empty($config)) {
            $this->config = array_merge($this->config, $config);
        }
        $this->riak = $this->getRiakInstance();
        $this->bucket = new Riak\Bucket($this->getBucketName());
    }

    public function __set($name, $value) {
        if (in_array($name, $this->attributes())) {
            $this->_data[$name] = $value;
        }
    }

    public function __get($name) {
        if (array_key_exists($name, $this->_data)) {
            return $this->_data[$name];
        }
        return FALSE;
    }

    public function __call($name, $arguments) {
        if (method_exists($this,$name)) {
            return call_user_func([$this, $name], $arguments);
        }
        if (substr($name, 0, 3) == 'set') {
            $attr = strtolower(substr($name, 3));
            $this->$attr = $arguments;
            return $this;
        }
        if (substr($name, 0, 3) == 'get') {
            $attr = strtolower(substr($name, 3));
            return $this->$attr;
        }
    }

    private function getRiakInstance(){
        if (empty($this->riak)) {
            $nodes = (new Riak\Node\Builder())
                    ->atHost($this->config['host'])
                    ->onPort($this->config['port'])
                    ->build();
            $this->riak = new Riak([$nodes]);
        }
        return $this->riak;
    }

    public function getData(){
        $attributes = $this->attributes();
        $data = [];
        foreach ($attributes as $attribute) {
            $data[$attribute] = $this->$attribute;
        }
        return $data;
    }

    public function setData($data = []) {
        foreach ($data as $key => $value) {
            $this->$key = $value;
        }
        return $this;
    }

    /**
     * save
     * @param bool $runValidation
     * @param null $attributeNames
     * @return bool
     */
    public function save() {
        $response = (new \Basho\Riak\Command\Builder\StoreObject($this->riak))
            ->buildBucket($this->getBucketName())
            ->buildJsonObject($this->getData())
            ->build()
            ->execute();
        if ($response->getCode() >= 200 && $response->getCode() < 300) {
            $this->key = $response->getLocation()->getKey();
        }
    }


    /**
     * findOne
     * @param $condition
     * @return RiakModelInterface
     */
    public static function findOne($condition) {
        /*$self = new static();
        $response = (new \Basho\Riak\Command\Builder\FetchObject())
            ->buildLocation('rufus', 'users')
            ->build()
            ->execute();*/
    }


    /**
     * delete
     * @return false|int
     * @throws \Exception
     */
    public function delete() {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    /**
     * update
     * @param bool $runValidation
     * @param null $attributeNames
     * @return false|int
     * @throws \Exception
     */
    public function update($runValidation = TRUE, $attributeNames = NULL) {

    }

    /**
     * insert
     * @param bool $runValidation
     * @param null $attributes
     * @return bool
     * @throws \Exception
     */
    public function insert($runValidation = TRUE, $attributes = NULL) {

    }

    public function getKey(){
        return $this->key;
    }

    public function getAttribute($name) {
        $attributes = $this->attributes();
        if (isset($attributes[$name])) {
            return $attributes[$name];
        }
    }

    public function setAttribute($name, $value) {
        die("ok");
    }

    public function getAttributes($names = NULL, $except = []) {
        return $this->attributes();
    }

    public function setAttributes($values, $safeOnly = TRUE) {
        die("OK");
    }

    public function attributes() {
        return [];
    }
}